/**
 * @description       : 
 * @author            : lucas.correia.d.melo@accenture.com
 * @group             : 
 * @last modified on  : 07-14-2022
 * @last modified by  : lucas.correia.d.melo@accenture.com
**/
public without sharing class Calculadora {
    static Integer a ;
    static Integer b ;
    
    public void somar(Integer a , Integer b) {       
        System.debug(a + b);
    }//teste
}