name: Salesforce Deploy - UAT

on:
  pull_request:
    branches:
      - UAT

  workflow_dispatch:

jobs:
  deploy-uat:
    name: Deploy Salesforce - UAT
    runs-on: ubuntu-latest
    environment: Group_Var
    
    steps:

      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version

      # 3. Criar arquivo da chave JWT
      - name: Create JWT Key
        run: |
          printf '%s\n' "${{ secrets.SF_JWT_KEY }}" > server.key
          chmod 600 server.key

      # 4. Autenticação na org UAT
      - name: Authenticate Salesforce UAT
        run: |
          sf org login jwt \
            --username "${{ secrets.SF_USERNAME }}" \
            --client-id "${{ secrets.SF_CLIENT_ID }}" \
            --jwt-key-file server.key \
            --instance-url "${{ secrets.SF_INSTANCE_URL }}" \
            --alias UAT

      # 5. Verificar autenticação
      - name: Check Salesforce Authentication
        run: |
          sf org display --target-org UAT

      - name: Extração de class de teste
        run: |
          testClassesSanitized=$(
            grep -oP '(?<=<members>).*?(?=</members>)' "${{ secrets.PATH_METADATA }}" | \
            while read className; do
              classFile="force-app/main/default/classes/${className}.cls"
              if [ -f "$classFile" ] && grep -qi "@isTest" "$classFile"; then
                echo "$className"
              fi
            done | tr '\n' ' '
          )
          printf "Classes encontradas: $testClassesSanitized"
          printf "TEST_CLASSES=$testClassesSanitized" >> "$GITHUB_ENV"

      - name: Validar deploy
        run: |
          TEST_FLAGS=""
          for cls in $TEST_CLASSES; do
            TEST_FLAGS="$TEST_FLAGS --tests $cls"
          done

          sf project deploy validate \
            --manifest "${{ secrets.PATH_METADATA }}" \
            --target-org UAT \
            --test-level RunSpecifiedTests \
            $TEST_FLAGS \
            --wait 120

      # 7. Deploy no UAT
      - name: Deploy to UAT
        run: |
          TEST_FLAGS=""
            for cls in $TEST_CLASSES; do
              TEST_FLAGS="$TEST_FLAGS --tests $cls"
            done

          sf project deploy start \
            --manifest manifest/package.xml \
            --target-org UAT \
            --test-level RunSpecifiedTests \
            $TEST_FLAGS \
            --wait 120
